// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Greeting(Props) {
  var name = Props.name;
  return React.createElement("div", undefined, "Hello! " + name);
}

var make = Greeting;

exports.make = make;
/* react Not a pure module */
