// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Greeting$Whatever = require("./Greeting.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Greeting$Whatever.make, {
          name: "Parcel"
        }), "app");

/*  Not a pure module */
